### PR TITLE
chore: Update remaining translations

### PR DESCRIPTION
**Pull request by machour**
Following up on #408, this PR will update the remaining translations.
Still waiting on `nl`

- Update TR translations. Thanks goes to @abdurrahmanekr

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
Thank you so much @abdurrahmanekr 🎉 

@RolfKoenders any chance you have a few minutes to quickly address a few translation strings? 🙏 
No worries if not :)

**Comment by housseindjirdeh** [comment]
@machour do you think we can suffice relying on Google Translate for these strings?

**Comment by machour** [comment]
@housseindjirdeh done buddy. Marked them with a comment so that translators will double check them

**Comment by housseindjirdeh** [comment]
Thanks so much buddy @machour 🎉

**Pull request merged**
