### PR TITLE
Upgrade redux persist

### PR DESCRIPTION
**Pull request by Arjun-sna**
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | iPhone 7, Onplus 5 |
| Bug fix?         | no      |
| New feature?     | no      |
| Includes tests?  | no      |
| All Tests pass?  | yes      |

---

### CODE REVIEW

**Comment by chinesedfan** [comment]
@Arjun-sna Can you share some details of this upgrade, i.e. advantages vs disadvantages?

**Comment by housseindjirdeh** [comment]
Looks like there were quite a few API changes, even if there were specific improvements besides changing the API -> always a good idea to stay updated where possible 👍🏾

Thanks a ton @Arjun-sna 🙌

**Comment by housseindjirdeh** [comment]
Someone should pull this down and test on their device/emulator before merging however. Will let y’all know when I get the chance to do it today/tomorrow

**Comment by housseindjirdeh** [comment]
Works well in my simulator 👍 

Thanks again @Arjun-sna!

**Pull request merged**
