### PR TITLE
refactor(*): cleanup code using prettier

### PR DESCRIPTION
**Pull request by andrewda**
Under normal conditions, prettier is only run on the lines of code that are changes in that commit. This cleans up all the code that doesn't currently conform to our prettier configuration, making the style completely consistent across all files again (and fixes the failing CI).

The command to run this cleanup yourself:

```bash
$ prettier --single-quote --trailing-comma es5 --write "**/*.js"
$ # or
$ yarn prettier
```

### CODE REVIEW

**Comment by lex111** [comment]
> The command to run this cleanup yourself:

Can it make sense to add this command as an npm-script in `package.json`?

**Comment by andrewda** [comment]
@lex111 Yes! Good idea, will do that now.

**Comment by andrewda** [comment]
@lex111 `yarn prettier` should do the trick now!

**Comment by andrewda** [comment]
@machour Yep - I'll set that up in another PR.

**Pull request merged**
