### PR TITLE
chore: Add changelog using standard-changelog

### PR DESCRIPTION
**Pull request by machour**
## Description

Reopening #504 using an automated tool, let's do this overdue changelog thing! 🎉

### CODE REVIEW

**Comment by machour** [comment]
Here's how the ChangeLog looks for now: https://gist.github.com/machour/6a6e41ec696a198021fb613f10e58a02

I generated it using `./node_modules/.bin/standard-changelog --first-release` then edited the result according to my archeologic researches made in #504.

Still need to : 

- [ ] Polish the generated file
- [ ] Add the links for < 1.3.0
- [ ] Wait for a few PRs to get merged and sync the file to see how it goes
- [ ] Document the proper workflow for releases (I think we need to `git tag` && `git push --tags` before re-generating the file)

**Comment by housseindjirdeh** [comment]
Amazing - how does the library work? Do we need to re-run the command everytime a commit is merged?

**Comment by machour** [comment]
I'm still unclear about the workflow, but I think this would have to be ran once per release.

**Comment by machour** [comment]
Pfiou, time flies :)
Closing this irrelevant PR.

**Pull request closed without merging**
