### PR TITLE
chore: update french translations

### PR DESCRIPTION
**Pull request by machour**
Translated english strings.

Other languages still need to be updated!

### CODE REVIEW

**Comment by machour** [comment]
@abdurrahmanekr @anaskhan96 @RolfKoenders @arthurdenner

Can you guys help us with those small translations?

- markAllAsRead: 'Mark all as read
- commentActions: 'Comment Actions'
- editCommentTitle: 'Edit Comment'
- editAction: 'Edit'
- deleteAction: 'Delete'

Please reply to this comment with the 5 translations in your language, I'll make sure they get merged in. Otherwise we'll have to rely on Google Translate and might not be really accurate.

Thanks in advance !

**Comment by abdurrahmanekr** [comment]
Turkish Translations:
- markAllAsRead: 'Hepsini okundu olarak işaretle'
- commentActions: 'Yorum Hareketleri'
- editCommentTitle: 'Yorumu Düzenle'
- editAction: 'Düzenle'
- deleteAction: 'Sil'

**Comment by jouderianjr** [comment]
Hey @machour was missing only one key in pt-br, just created the PR

**Comment by machour** [comment]
@abdurrahmanekr Thank you so much! Sorry I missed a few other strings 🙏 

      connectingToGitHub: 'Connecting to GitHub...',
      preparingGitPoint: 'Preparing GitPoint...',
      cancel: 'CANCEL',

**Comment by abdurrahmanekr** [comment]
- connectingToGitHub: 'GitHub\'a Bağlanılıyor...',
- preparingGitPoint: 'GitPoint Hazırlanıyor...',
- cancel: 'İPTAL'
👍

**Comment by machour** [comment]
Thank you again @abdurrahmanekr !

**Pull request merged**
