### PR TITLE
refactor: use styled-components in entity-info

### PR DESCRIPTION
**Pull request by MrLoh**
related to #532

### CODE REVIEW

**Comment by MrLoh** [comment]
I factored everything related to the styling of the component into the styled-component parts, using attrs

**Comment by housseindjirdeh** [comment]
This is awesome, thank you @MrLoh 🎉

**Comment by ocarreterom** [comment]
Typo
https://github.com/gitpoint/git-point/blob/b30e64b2cb9e5d514c10f182e01caf1da25e7269/src/components/entity-info.component.js#L27
@MrLoh

**Comment by MrLoh** [comment]
Fixed in #573

**Pull request merged**
