### PR TITLE
fix(language-colors): fix/add language colors

### PR DESCRIPTION
**Pull request by Charliekenney23**
Fixes C++ color and adds some missing languages.

### CODE REVIEW

**Comment by lex111** [comment]
@Charliekenney23 hello and welcome! Why so many files in PR? I mean, there should be like two files: `.all-contributorsrc` and `src/config/colors.js`. Can we remove the others?

**Comment by Charliekenney23** [comment]
Yikes, just realized that. I guess they were mysteriously added in the build step. Let me reset head and recommit only those files.

**Comment by Charliekenney23** [comment]
All set. Thanks for the warm welcome! I'm really enjoying the app. Hope to contribute some more code soon!

**Comment by housseindjirdeh** [comment]
So glad you like the app mate, don't hesitate to contribute some more anytime and we're more than happy to help you understand how any part of the codebase works!

**Pull request merged**
