### PR TITLE
fix(ui): Fix Bio section in auth-profile

### PR DESCRIPTION
**Pull request by jouderianjr**
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.0      |
| Devices tested?  | Android version Nougat |
| Bug fix?         | yes      |
| New feature?     | no      |
| Includes tests?  | no      |
| All Tests pass?  | yes      |
| Related ticket?  | #569         |

---

## Screenshots

| Before   | After    |
| -------- | -------- |
| beforeauth | subtitlewithfontweight |

## Description

After the react-native-elements update, we've lost some styles,
this commit removes ellipsize from bio text and set `fontWeight` to normal.

I'm still using the text as subtitle but we could just use as a title, has a similar style that the old subtitle.

| Title   | Subtitle    |
| -------- | -------- |
| title | subtitlewithfontweight |

### CODE REVIEW

**Comment by machour** [comment]
@jouderianjr echoing your suggestion, it would make more sense to use `title` instead of `subtitle`.

**Comment by alejandronanez** [comment]
@jouderianjr please feel free to merge either you use `title` or not.

**Comment by jouderianjr** [comment]
I'm just changing to `title` right now 💃 but I've noticed that I forgot about `user-profile.screen`, I'll fix it in that screen also.

**Comment by jouderianjr** [comment]
Merging, Thank you everyone 💃

**Pull request merged**
