### PR TITLE
chore: remastered german translation

### PR DESCRIPTION
**Pull request by FlonTaut**
chore: remastered german translation

| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | All |
| Bug fix?         | no      |
| New feature?     | no      |
| Includes tests?  | no      |
| All Tests pass?  | ?      |
| Related ticket?  |        |

---

## Description

Hey guys, im back with a new PR 👍 

I remastered the whole German translation file.

While translating i realized some string are not included in the translations.

Meant are the strings used in issue/pr actions. f.e.
```{actor} deleted this branch```
or
```{actor} added {label}```

These strings or similar strings are missing.

Should i open a new issue for this or is it wanted this way somehow?

I realized i missed to create a new branch at my fork, sorry bout that 😄

### CODE REVIEW

**Comment by chinesedfan** [comment]
@FlonTaut Welcome back! Can you show more details about the missing strings? Currently, those strings are extracted by `scripts/extract-i18n.js`.

**Comment by FlonTaut** [comment]
@chinesedfan here you can see a screenshot. (language is set to german)
This is the release version from app store but its the same on master branch.
And i cant find these strings anywhere:

screen

**Comment by chinesedfan** [comment]
@FlonTaut You're right. Please open a new issue and record all missing places that you found. Those words have never been included in our i18n files, so the script could not extract them.

**Comment by machour** [comment]
Thank you!

**Pull request merged**
