### PR TITLE
fix(status-bar): change color depending on background

### PR DESCRIPTION
**Pull request by darecki**
After the fix the repository screen looks like this:
repository-fixed

### CODE REVIEW

**Comment by FlorianTaut** [comment]
Very cool!

**Comment by RolfKoenders** [comment]
Hee @darecki! Thanks for this! Looks good! The only thing im wondering is why the stars and forks are not showing up?

**Comment by andrewda** [comment]
@RolfKoenders I just realized that may have been one of my changes last night to try and make the numbers stop jumping around while loading data. I didn't think about a value of 0 for the stars and forks being falsey! Will fix ASAP.

**Comment by henrikra** [comment]
Please fix the conflicts :D @darecki

**Comment by andrewda** [comment]
Conflicts have been resolved. If this works, should be good to go!

**Comment by andrewda** [comment]
@gitpoint/maintainers any update here? Is this ready to go?

**Comment by alejandronanez** [comment]
@andrewda I think so, yes.

**Comment by machour** [comment]
Just tested this patch on my Android OnePlus 3T, the behavior is quiet weird:

1. Opened the app: Events screen: no status bar at all
2. Navigated to my profile: status bar (dark bg, white fg)
3. Back to Events: status bar (dark bg, white fg)
4. Search tab: no status bar
5. Back to my profile screen: *no status bar*
6. Events: no status bar again

I'm not sure this behavior is solely due to this PR, because if I run the app without applying it, I have no status bar at all in all the application screens..

**Comment by machour** [comment]
Houston, we have a problem.

TabNavigation & StatusBar don't play nice together, as the StatusBar isn't refreshed *every time* we change the active tab on Android & iOS. So if a screen implement a dark status bar, and another screen the light one, after a few clicks the last rendered StatusBar will always be displayed, no matter the screen you're on: https://github.com/react-community/react-navigation/issues/342

The only way out of this I see for now is to always use the same StatusBar coloring for all screens, until events/lifecycles are implemented in TabNavigator.

**Comment by emilklindt** [comment]
@machour I am experiencing this same thing on the project that I am currently working on.

Is there any plans to resolve this issue in the near future?

**Comment by machour** [comment]
@emilklindt that's up to `react-navigation` maintainers.

Meanwhile, @jouderianjr seems to be experimenting with a rather efficient workaround using `onNavigationStateChange`, check this commit for more information: https://github.com/jouderianjr/git-point/commit/c89ad3b500386aa3a051659de737bc0332877d6b

**Comment by chinesedfan** [comment]
@jouderianjr Is this PR what you did in #641?

**Comment by machour** [comment]
Yes, this one can be closed @chinesedfan

**Pull request closed without merging**
