### PR TITLE
Align event text

### LINKED ISSUE #200: Non-aligned text on the home screen
- It would be great if the text is aligned as shown below in the image.
- The all of a sudden bulging text on the left looks odd & messy creating a bad experience.
- Aligning the text as shown would make it look neat & even.

gpi

PS: Please ignore the editing, did that on my phone :smile:

### PR DESCRIPTION
**Pull request by lex111**
Closes #200.

Before | After 
| - | - 
image |  image

### CODE REVIEW

**Comment by RolfKoenders** [comment]
Like i said in #200 i like it! :+1:

**Comment by introwit** [comment]
@lex111 thank you for your work on this Alexey ❤️

**Comment by Antoine38660** [comment]
Yes, I like it too 😄 👍

**Comment by housseindjirdeh** [comment]
Looks solid thank you @lex111 🎉 

And thanks a million for the suggestion @introwit <3

**Pull request merged**
