### PR TITLE
docs(readme): add table of contents section

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This can help browser the document faster and easier!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks @housseindjirdeh, I can add a npm script to help update it in future if you like it.

**Comment by housseindjirdeh** [comment]
That would be amazing 😍 Appreciate you thinking of ways to improve it, thanks a million

**Comment by PeterDaveHello** [comment]
Will do it tomorrow, time for me to sleep now :)

**Comment by PeterDaveHello** [comment]
Done in #388

**Pull request merged**
