### PR TITLE
fix(issues): handle PR struct correctly

### PR DESCRIPTION
**Pull request by machour**
We were having an `Uncaught error in promise` due to the `issueParam` navigation state sometime being a `PullRequest` instead of an `Issue` .. This caused the Merge permission check & diff to fail.

Here's a hotfix for now, but this definitely call for a big clean up post release, and why not a separate `src/pulls/` implementation.

### CODE REVIEW

**Comment by machour** [comment]
Prettier messed the diff a bit, here is it without whitespaces changes : 
  https://github.com/gitpoint/git-point/pull/380/files?w=1

I did only modify the changes near the if(), prettier did the rest.

**Comment by chinesedfan** [comment]
@machour @housseindjirdeh How about my #332 ? I think it solved the same problem.

**Comment by machour** [comment]
@chinesedfan oh man, so sorry, didn't know this was already addressed by your PR!
@housseindjirdeh please check #332 before this one, the fix is cleaner!

**Comment by housseindjirdeh** [comment]
Just merged in #332, apologies for not merging that one in sooner and having this duplication happen @machour 😞

**Comment by machour** [comment]
No problems, and thanks again @chinesedfan <3

**Pull request closed without merging**
