### PR TITLE
MIssing can't login translation

### PR DESCRIPTION
**Pull request by evenzdev**
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | Samsung Galaxy S7 |
| Bug fix?         | yes      |
| New feature?     | no      |
| Includes tests?  | no      |
| All Tests pass?  | yes      |
| Related ticket?  | no ticket available        |

---

## Description

Simplified Chinese translation for unable to login was missing, this has now been added.

### CODE REVIEW

**Comment by lex111** [comment]
Hi @evenzdev!

Can add other missing translations at the same time? Look by search on `''`

image

**Comment by evenzdev** [comment]
@lex111 oo didn't see the other missing ones, thought it was weird only one was missing haha, I will update this!

**Comment by lex111** [comment]
friendly ping @evenzdev

**Comment by housseindjirdeh** [comment]
Thanks a million for this @evenzdev 🙌 

If you get the chance to take a look at the others (no rush and only if you feel like it!) we can merge this in :)

**Comment by chinesedfan** [comment]
@evenzdev I added missing translations and fixed some sentences on your branch, so that we can merge it.

**Comment by lex111** [comment]
@evenzdev @Chandrasekar-G thank you both! :jack_o_lantern:

**Pull request merged**
