### PR TITLE
chore(update): update react-native to 0.48.1

### PR DESCRIPTION
**Pull request by lex111**

### CODE REVIEW

**Comment by andrewda** [comment]
We might want to look into [Greenkeeper](https://github.com/apps/greenkeeper) to keep dependencies up to date 👍

**Comment by lex111** [comment]
@andrewda yep, it was great!

**Comment by lex111** [comment]
@andrewda oh, we can update to 0.48.2, what do we do?

**Comment by housseindjirdeh** [comment]
Agreed @andrewda, anything to keep updates manageable would be extremely useful. Opened #321 to address this.

@lex111 I say we merge this in and try to explore Greenkeeper instead of worrying about updating this PR for 48.2 :)

**Pull request merged**
