### PR TITLE
Adding Indonesia Translation

### PR DESCRIPTION
**Pull request by raihan71**
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | Samsung J4... |
| Bug fix?         | yes |
| New feature?     | yes |
| Includes tests?  | no |
| All Tests pass?  | yes |
| Related ticket?  | #439   |

---

## Screenshots

| Before   | After    |
| -------- | -------- |
|before|after|

## Description

* Adding Bahasa Translation
* Fixing Norsk Flag Language

### CODE REVIEW

**Comment by raihan71** [comment]
hi @lex111 this is my first PR, let me know what you think

**Comment by Jpfonseca** [comment]
Seems good to me. But I ain't a maintainer 😅

**Comment by raihan71** [comment]
> Seems good to me. But I ain't a maintainer 😅

aa haha, well hope the real one read this asap

**Review by lex111 — APPROVED** [review]

**Comment by lex111** [comment]
Hi @raihan71 

Sorry for the delay, despite discontinuation of this application maintaining, I think in gratitude to accept your pull request, maybe in the future your translation will be useful.

Thanks for the contribution!

**Comment by raihan71** [comment]
> Hi @raihan71
> 
> Sorry for the delay, despite discontinuation of this application maintaining, I think in gratitude to accept your pull request, maybe in the future your translation will be useful.
> 
> Thanks for the contribution!

hi there, thank you so much..

**Pull request merged**
