### PR TITLE
chore(lint): Add stylelint script

### PR DESCRIPTION
**Pull request by chinesedfan**
As discussed in #604, I integrated `stylelint` by following styled-components [tutorial](https://www.styled-components.com/docs/tooling#stylelint).

Please notice that even with the official `stylelint-processor-styled-components`, `stylelint` is not 100% compatible with styled-components. So I added some customized rules.

```
  "rules": {
    // 1
    "block-no-empty": null,
    // Inspired by https://github.com/styled-components/css-to-react-native/blob/master/src/tokenTypes.js#L31
    // to avoid unitless shorthands properties crash
    "declaration-property-value-whitelist": {
      "margin": ["/^(0|[+-]?(\\d*\\.)?\\d+px)( (0|[+-]?(\\d*\\.)?\\d+px))?$/"],
      "padding": ["/^(0|[+-]?(\\d*\\.)?\\d+px)( (0|[+-]?(\\d*\\.)?\\d+px))?$/"],
    },
    // 2
    "declaration-colon-newline-after": null,
    "value-list-max-empty-lines": null
  },
```

- Cases like 1, i.e. [comment-input.component.js](https://github.com/gitpoint/git-point/blob/master/src/components/comment-input.component.js#L42)
```
const PostButtonIcon = styled(Icon).attrs({
  color: props => (props.disabled ? colors.grey : colors.primaryDark),
})``; // here will generate an empty block
```

- Cases like 2, i.e. [badge.component.js](https://github.com/gitpoint/git-point/blob/master/src/components/badge.component.js#L28)
```
const BadgeText = styled.Text`
  ${{ ...fonts.fontPrimaryBold }};
  background-color: transparent;
  ${({ largeText }) =>
    `font-size: ${largeText ? normalize(9.5) : normalize(7)};`};
`;
```
It will be parsed as,
```
const BadgeText = styled.Text`
  ${{ ...fonts.fontPrimaryBold }};
  background-color: transparent;
  -styled-mixin1: dummyValue
/* dummyComment */;
`;
```

### CODE REVIEW

**Comment by machour** [comment]
Thanks for looking into this! For the second case, would formatting the rule as you suggested in #648 solve the compatibility issue?

**Comment by chinesedfan** [comment]
@machour No, rules in case 2 will only affect multi-lines declarations. And I replied with my understandings of those 2 styles in #648 directly.

**Comment by machour** [comment]
Applied this PR diff on my macbook, got the following error message:
screen shot 2017-12-04 at 2 31 25 pm

Any clue what might be going on?

**Comment by chinesedfan** [comment]
@machour I searched around and found that `$export is not a function` was usually caused by [circular dependencies](https://stackoverflow.com/questions/43222249/webpack-2-3-3-typeerror-export-is-not-a-function). After this PR applied, 2 different versions of `core-js` were installed.

It is an annoy feature of `yarn` that `yarn add <pkg>` only updates dependencies of pkg, but doesn't update those already in `yarn.lock`. Finally, I fixed it by keeping only one version of `core-js`.(In fact, if we just installed core-js 2.5.1, there were still no errors)

**Pull request merged**
