### PR TITLE
refactor(styles): Migrate LabelButton

### PR DESCRIPTION
**Pull request by josenaranjo**
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.0      |
| Devices tested?  | iPhone 7 |
| Bug fix?         | no      |
| New feature?     | no      |
| Includes tests?  | no      |
| All Tests pass?  | no      |
| Related ticket?  | #532      |

LabelButton's tests are not passing, I already tried to fix it, but didn't find the reason why it is failing. Please let me know if you have any hint.

---

## Screenshots

| Before   | After    |
| -------- | -------- |
| before | after
) |

## Description
Refactored LabelButton to render a LabelButton large or small depending on largeWithTag prop

### CODE REVIEW

**Comment by chinesedfan** [comment]
@josenaranjo I am afraid that it is better to keep as one component and control properties by props. For example,

```
const LabelButton = styled.Button`
    font-size: ${props => props.largeWithTag ? 13 : 12};
`;
```

**Comment by machour** [comment]
Hi @josenaranjo, friendly ping, are you still up for this one? Let us know 🙏

**Comment by chinesedfan** [comment]
@josenaranjo Sorry, #727 will take over your work. But please feel free to help our project at any time in the future!

**Comment by machour** [comment]
#727 was merged in, closing this stale PR

**Pull request closed without merging**
