### PR TITLE
Update nl.js

### PR DESCRIPTION
**Pull request by Eliottiosdevs**
Updated the translations to more polite-form
Updated google-translate phrases
Updated incorrect tenses
Updated English tenses

### CODE REVIEW

**Comment by Eliottiosdevs** [comment]
Any idea when it will be merged?

**Comment by lex111** [comment]
@Eliottiosdevs today or tomorrow, @housseindjirdeh  will merge.

**Comment by Eliottiosdevs** [comment]
Thanks @housseindjirdeh for merging!

**Comment by housseindjirdeh** [comment]
Not at all, thank YOU for contributing my friend @Eliottiosdevs  :)

**Pull request merged**
