### PR TITLE
fix(repo): Show repo prefix for search repo result

### LINKED ISSUE #252: Repository search: show user/organisation prefix
Currently, if I search for a repository, the displayed repository name doesn't show the user/repo prefix, making it really hard to guess what repository is the one I'm searching for : 

Better search results

### PR DESCRIPTION
**Pull request by reyhansofian**
Closes #252 

- [x] show repo prefix

# Preview

image

### CODE REVIEW

**Comment by chinesedfan** [comment]
@housseindjirdeh Please notice that `/src/user/screens/repository-list.screen.js` also uses the same component. So this PR changes behaves in that page.

All repositories of that page belong to the same user and share the same prefix. Does it redundant?

**Comment by housseindjirdeh** [comment]
@chinesedfan have no idea how I missed this :(

You're 100% right and I've pushed a commit to #409 so that it doesn't show for the current active user's list of repos. Everywhere else it would still show.

**Comment by chinesedfan** [comment]
@housseindjirdeh Never mind. I know maintaining such a great project is very busy. Even watched, I receive lots of notifications everyday. 😆

**Comment by housseindjirdeh** [comment]
Haha before GitPoint I would rarely get notifications. My notifications list becomes _massive_ everyday now :O

But with that new `Mark all notifications as read` feature by @lex111, things might just be a lot better 😉

**Pull request merged**
