### PR TITLE
iPad support

### LINKED ISSUE #37: iPad support
I don't know how much work it is to support iPad size classes but I would absolutely love to pay $10 for this conditional on supporting iPad (where I do most of my team communication - and development on my desktop). I get that it's a free download but I so badly want there to be a good iPad client :)

### PR DESCRIPTION
**Pull request by patw0929**
Fixed #37.

Thanks for the awesome project!

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
I owe you one mate :tada: 

Just wanted to ask however - does this PR mean that a scaled version of the app will be now available on the app store on iPad? Is it not currently available on the app store? Genuinely curious as I'm not sure :)

**Comment by patw0929** [comment]
Yap, it will be the iPad version on the app store.

Also shown `This app is designed for both iPhone and iPad` in the left side on the app store:
image

In itunes connect, we also have to prepare the iPad screenshots for preview.

I'm not sure if I missing other things, please kindly review for this. 😃

**Comment by staabm** [comment]
@patw0929 could you add a screenshot to this PR so one can see how the UI looks like?

**Comment by patw0929** [comment]
Screenshots on iPad Air 2 Simulator:

**Comment by staabm** [comment]
ohh nice. much better as it currently is. great job!

**Comment by housseindjirdeh** [comment]
Oh my god this is beautiful <3. Thank you so much @patw0929.

Will remember to upload iPad screenshots in the next update. Goal is to have that it up in the App Store by Monday 🎉

**Comment by housseindjirdeh** [comment]
@patw0929 oops forgot to mention earlier, please don't forget to add yourself to the contributors list with `yarn contributors:add`! You can do that as a separate PR if you like :)

**Comment by tylerbenson** [comment]
@patw0929 awesome! Thanks so much.

**Pull request merged**
