### PR TITLE
Adding myself as contributor

### PR DESCRIPTION
**Pull request by siderio2**
Sorry, but I forgot to do this before...

### CODE REVIEW

**Comment by andrewda** [comment]
Hey @siderio2 - could you apply 6160553 to branch that's fresh with master? Might mess up some history if we merge in the same changes as #452.

**Comment by housseindjirdeh** [comment]
Yep looks like this is applying the same translation changes. If you can cherry-pick that specific commit that would be awesome :) Otherwise, you can just create a fresh branch, add yourself as a contributor and put up a PR for that :man_dancing:

**Comment by siderio2** [comment]
Ok, newbie mistake, sorry. Will do later when I arrive home :smiley:

**Comment by housseindjirdeh** [comment]
@siderio2 no worries mate :) Take your time!

**Comment by housseindjirdeh** [comment]
Looks like you've set up a separate PR #461 for this, cheers mate thank you :tada:

**Pull request closed without merging**
