### PR TITLE
Show message if no contributors found

### PR DESCRIPTION
**Pull request by lex111**
Preview:
image

### CODE REVIEW

**Comment by andrewda** [comment]
Out of curiosity, does this happen only on empty repositories?

**Comment by lex111** [comment]
@andrewda probably yes, eg here is [my test repository](https://github.com/lex111/test).
But all the same, it seems to me necessary to process such situation.

**Comment by andrewda** [comment]
Yep! Looks good to me!

**Comment by lex111** [comment]
@housseindjirdeh I did this initially, but it was not very pretty, I'll show you a screenshot later, so you can see it. This is because the list of contributors is not a list (SectionList).

**Comment by lex111** [comment]
@housseindjirdeh here is how the message will look if it is pasted using the `ListItem`, it looks like this because of the padding of the container. But even if this is fixed, it's still not very suitable for this block, because this is not a list.

image

Instead, I would add the bottom line to the title, like so:

image

**Comment by housseindjirdeh** [comment]
Ah that's a very fair point @lex111 - how about we we show the `ListItem` with the message within if there are no contributors but leave it the way it is (without the `ListItem`) if members are present?

**Comment by lex111** [comment]
@housseindjirdeh correctly, did I understand that we are doing the same as on the first screenshot, despite the fact that it does not look so good?

**Comment by housseindjirdeh** [comment]
Ah you're right it's a little more complicated then that - just dived in a bit. Something like this should work: 

```
import React from 'react';

import {
  StyleSheet,
  View,
  Text,
  FlatList,
  TouchableHighlight,
  Image,
} from 'react-native';

import { colors, fonts } from 'config';
import { List, ListItem} from 'react-native-elements';

type Props = {
  title: string,
  members: Array,
  smallTitle: string,
  navigation: Object
};

const styles = StyleSheet.create({
  container: {
    marginTop: 30,
  },
  avatarContainer: {
    //..
  },
  avatar: {
    //.. 
  },
  list: {
    marginTop: 0,
  },
  sectionTitle: {
    color: colors.black,
    ...fonts.fontPrimaryBold,
    marginBottom: 10,
    paddingLeft: 15,
  },
  sectionTitleSmall: {
    color: colors.primaryDark,
    ...fonts.fontPrimarySemiBold,
    marginBottom: 10,
    paddingLeft: 15,
  },
  listTitle: {
    color: colors.black,
    ...fonts.fontPrimary,
  },
});

export const MembersList = ({
  title,
  members,
  smallTitle,
  navigation,
}: Props) =>
  <View style={[styles.container]}>
    <Text style={smallTitle ? styles.sectionTitleSmall : styles.sectionTitle}>
      {title}
    </Text>

    {!members.length &&
    <List containerStyle={styles.list}>
        <ListItem
          title={'No contributors found'}
          titleStyle={styles.listTitle}
          hideChevron
        />
      </List>
    }

    {members.length &&
      <View style={styles.listPadding}>
        <FlatList 
          // ...
        />
      </View>
    }
  </View>;
```

**Comment by housseindjirdeh** [comment]
1. Don't think `containerStyle` prop is being used (I know it's outside the scope of this PR but please feel free to just remove it)
2. Needs a little tinkering with the styles but I think what I have above _roughly_ should make things work so it looks like this without any members:

image

**Comment by lex111** [comment]
@housseindjirdeh thanks for the support! Added only `paddingLeft` for FlatList, now it seems to be good.

**Comment by lex111** [comment]
@housseindjirdeh resolved the conflict via GitHub :heavy_check_mark:

**Comment by housseindjirdeh** [comment]
Beautiful thank you matey 🎉

**Pull request merged**
