### PR TITLE
wip(test): add text normalization test

### PR DESCRIPTION
**Pull request by andrewda**
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | all      |
| Devices tested?  | n/a |
| Bug fix?         | no      |
| New feature?     | no      |
| Includes tests?  | yes      |
| All Tests pass?  | yes*      |
| Related ticket?  | #518        |

---

## Description

Adds a test for the `text-normalize` file. Currently WIP.

### CODE REVIEW

**Comment by andrewda** [comment]
Need to figure out how to reset the mock each time. The first run `mockRequiredClasses` values are carried on to all the remaining tests. Not sure how to fix this.

**Comment by alejandronanez** [comment]
@andrewda have you tried with `beforeEach` / `afterEach`?

**Comment by andrewda** [comment]
@alejandronanez What should I use them for?

**Comment by alejandronanez** [comment]
@andrewda I think you can reset the mock for every test that is run. (or I am just misunderstanding everything 😞 )

**Comment by andrewda** [comment]
Yea, but I'm not sure how to reset _just_ the Dimension and PixelRatio mocks, instead of _everything_ (like the ones defined in testenv.js).

**Comment by machour** [comment]
@andrewda I had a look at this PR and after a lot of trial and error, the only working thing I can come up with is chaining .mockReturnValueOnce() calls:

```js
jest.mock('Dimensions', () => ({
  get: jest
    .fn()
    .mockReturnValueOnce(mockScreens.iPhone5)
    .mockReturnValueOnce(mockScreens.iPhone6),
}));
jest.mock('PixelRatio', () => ({
  get: jest
    .fn()
    .mockReturnValueOnce(2)
    .mockReturnValueOnce(2),
}));

describe('Normalize Text', () => {
  // iOS Devices

  it('should normalize correctly on iPhone 5', () => {
    const { normalize } = require('config');
    expect(normalize(1)).toEqual(0.95);
  });

  it('should normalize correctly on iPhone 6', () => {
    const { normalize } = require('config');
    expect(normalize(1)).toEqual(0.95);
  });
```

This require a change in the `src/config/normalize-text.js` file where `Dimensions.get('window')` is currently called twice (and as we mock **once** a single test ends up consuming two mocks).

**Comment by chinesedfan** [comment]
How about [`jest.unmock(moduleName)`](https://facebook.github.io/jest/docs/en/jest-object.html#jestunmockmodulename)?

**Comment by machour** [comment]
Didn't work for me. If you console.log() in mockClassWithGetter , you'll see the log only once

**Comment by chinesedfan** [comment]
Jest@24 provides [jest.isolateModules(fn)](https://jestjs.io/docs/en/jest-object#jestisolatemodulesfn). I think it is what we want.

**Comment by andrewda** [comment]
Closing in favor of https://github.com/gitpoint/git-point/pull/899 (thanks @chinesedfan!)

**Pull request closed without merging**
